# snyk-ado-cli-caller.yml
trigger:
- manual

# Example on calling template from another org which will required setup a server connection to that org repository
# resources:
#   repositories:
#   - repository: ExternalTemplateRepo # alias for the repository defined in resources
#     type: git
#     name: OtherOrgProject/TemplateRepo  # Replace with the name of the repo in the other organization
#     endpoint: OtherOrgServiceConnection  # Name of the service connection created earlier

jobs:
- job: BuildAndTest
  pool:
    vmImage: ubuntu-latest  # You can change this based on your requirements

  steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'   # Define the version of Node.js to install
    displayName: 'Install Node.js'

  # Install dependencies and build
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  # Reference the reusable Snyk template
  - template: snyk-ado-cli-template.yml  # Reference the reusable template
    parameters:
      SNYK_TOKEN: $(SNYK_TOKEN)  # Pass the SNYK_TOKEN from the variable group
      SNYK_FLAGS: '' # Pass custom snyk CLI flags
