# snyk-ado-cli-caller.yml
trigger:
- manual

# Example on calling template from another org which will required setup a server connection to that org repository
# resources:
#   repositories:
#   - repository: ExternalTemplateRepo # alias for the repository defined in resources
#     type: git
#     name: OtherOrgProject/TemplateRepo  # Replace with the name of the repo in the other organization
#     endpoint: OtherOrgServiceConnection  # Name of the service connection created earlier
    
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

steps:
  - template:
    parameters: snyk-ado-cli-template.yml
      SNYK_TOKEN: $(SNYK_TOKEN)
