# snyk-ado-cli-caller.yml
trigger:
  - manual

jobs:
  - job: BuildAndTest
    pool:
      vmImage: ubuntu-latest # You can change this based on your requirements

    steps:
      # Install Node.js
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x" # Define the version of Node.js to install
        displayName: "Install Node.js"

      # Install dependencies and build
      - script: |
          npm install
          npm run build
        displayName: "npm install and build"

      # Reference the reusable Snyk template
      - template: snyk-ado-cli-template.yml # Reference the reusable template
        parameters:
          SNYK_TOKEN: $(SNYK_TOKEN) # Pass the SNYK_TOKEN from the variable grou
